import os
from pydantic_settings import BaseSettings

class Settings(BaseSettings):
    SUMMARIZATION_MESSAGE_THRESHOLD: int = 5
    EMBEDDING_DIM: int = 384
    OVERVIEW_CACHE_TTL_SECONDS: int = 300
    DEFAULT_TOP_K: int = 4
    RERANKER_TOP_K: int = 6
    GRAPH_MAX_DEPTH: int = 3
    CONFIDENCE_THRESHOLD: float = 0.7

settings = Settings()

SUMMARIZATION_MESSAGE_THRESHOLD = settings.SUMMARIZATION_MESSAGE_THRESHOLD
EMBEDDING_DIM = settings.EMBEDDING_DIM
OVERVIEW_CACHE_TTL_SECONDS = settings.OVERVIEW_CACHE_TTL_SECONDS
DEFAULT_TOP_K = settings.DEFAULT_TOP_K
RERANKER_TOP_K = settings.RERANKER_TOP_K
GRAPH_MAX_DEPTH = settings.GRAPH_MAX_DEPTH
CONFIDENCE_THRESHOLD = settings.CONFIDENCE_THRESHOLD
